#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Busquedas")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTabla_De_Administradores(Tabla_De_Administradores instance);
    partial void UpdateTabla_De_Administradores(Tabla_De_Administradores instance);
    partial void DeleteTabla_De_Administradores(Tabla_De_Administradores instance);
    partial void InsertTabla_De_Anos(Tabla_De_Anos instance);
    partial void UpdateTabla_De_Anos(Tabla_De_Anos instance);
    partial void DeleteTabla_De_Anos(Tabla_De_Anos instance);
    partial void InsertTabla_De_Colegios(Tabla_De_Colegios instance);
    partial void UpdateTabla_De_Colegios(Tabla_De_Colegios instance);
    partial void DeleteTabla_De_Colegios(Tabla_De_Colegios instance);
    partial void InsertTabla_De_Ejercicios(Tabla_De_Ejercicios instance);
    partial void UpdateTabla_De_Ejercicios(Tabla_De_Ejercicios instance);
    partial void DeleteTabla_De_Ejercicios(Tabla_De_Ejercicios instance);
    partial void InsertTabla_De_Empresas(Tabla_De_Empresas instance);
    partial void UpdateTabla_De_Empresas(Tabla_De_Empresas instance);
    partial void DeleteTabla_De_Empresas(Tabla_De_Empresas instance);
    partial void InsertTabla_De_Materias(Tabla_De_Materias instance);
    partial void UpdateTabla_De_Materias(Tabla_De_Materias instance);
    partial void DeleteTabla_De_Materias(Tabla_De_Materias instance);
    partial void InsertTabla_De_Profesores(Tabla_De_Profesores instance);
    partial void UpdateTabla_De_Profesores(Tabla_De_Profesores instance);
    partial void DeleteTabla_De_Profesores(Tabla_De_Profesores instance);
    partial void InsertTabla_De_Temas(Tabla_De_Temas instance);
    partial void UpdateTabla_De_Temas(Tabla_De_Temas instance);
    partial void DeleteTabla_De_Temas(Tabla_De_Temas instance);
    partial void InsertTabla_Tipo_De_Institucion(Tabla_Tipo_De_Institucion instance);
    partial void UpdateTabla_Tipo_De_Institucion(Tabla_Tipo_De_Institucion instance);
    partial void DeleteTabla_Tipo_De_Institucion(Tabla_Tipo_De_Institucion instance);
    partial void InsertTabla_Tipo_De_Producto(Tabla_Tipo_De_Producto instance);
    partial void UpdateTabla_Tipo_De_Producto(Tabla_Tipo_De_Producto instance);
    partial void DeleteTabla_Tipo_De_Producto(Tabla_Tipo_De_Producto instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::Datos.Properties.Settings.Default.BusquedasConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tabla_Ubicacion_De_Los_Ejercicios> Tabla_Ubicacion_De_Los_Ejercicios
		{
			get
			{
				return this.GetTable<Tabla_Ubicacion_De_Los_Ejercicios>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_Busqueda_De_Ejercicios_Por_Etiquetas> Tabla_Busqueda_De_Ejercicios_Por_Etiquetas
		{
			get
			{
				return this.GetTable<Tabla_Busqueda_De_Ejercicios_Por_Etiquetas>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_De_Administradores> Tabla_De_Administradores
		{
			get
			{
				return this.GetTable<Tabla_De_Administradores>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_De_Anos> Tabla_De_Anos
		{
			get
			{
				return this.GetTable<Tabla_De_Anos>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_De_Colegios> Tabla_De_Colegios
		{
			get
			{
				return this.GetTable<Tabla_De_Colegios>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_De_Ejercicios> Tabla_De_Ejercicios
		{
			get
			{
				return this.GetTable<Tabla_De_Ejercicios>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_De_Empresas> Tabla_De_Empresas
		{
			get
			{
				return this.GetTable<Tabla_De_Empresas>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_De_Materias> Tabla_De_Materias
		{
			get
			{
				return this.GetTable<Tabla_De_Materias>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_De_Profesores> Tabla_De_Profesores
		{
			get
			{
				return this.GetTable<Tabla_De_Profesores>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_De_Temas> Tabla_De_Temas
		{
			get
			{
				return this.GetTable<Tabla_De_Temas>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_MATH_De_Ejercicios> Tabla_MATH_De_Ejercicios
		{
			get
			{
				return this.GetTable<Tabla_MATH_De_Ejercicios>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_Tipo_De_Institucion> Tabla_Tipo_De_Institucion
		{
			get
			{
				return this.GetTable<Tabla_Tipo_De_Institucion>();
			}
		}
		
		public System.Data.Linq.Table<Tabla_Tipo_De_Producto> Tabla_Tipo_De_Producto
		{
			get
			{
				return this.GetTable<Tabla_Tipo_De_Producto>();
			}
		}
		
		public System.Data.Linq.Table<Vista_Administradores> Vista_Administradores
		{
			get
			{
				return this.GetTable<Vista_Administradores>();
			}
		}
		
		public System.Data.Linq.Table<Vista_Buscar_Ejercicios> Vista_Buscar_Ejercicios
		{
			get
			{
				return this.GetTable<Vista_Buscar_Ejercicios>();
			}
		}
		
		public System.Data.Linq.Table<Vista_Buscar_Videos> Vista_Buscar_Videos
		{
			get
			{
				return this.GetTable<Vista_Buscar_Videos>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Buscar_En_Tabla_Anos")]
		public ISingleResult<Tabla_De_Anos> Buscar_En_Tabla_Anos([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ano", DbType="NVarChar(150)")] string ano)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ano);
			return ((ISingleResult<Tabla_De_Anos>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Mostrar_Ejercicios_Por_Profundidad_Del_Enunciado")]
		public ISingleResult<Tabla_MATH_De_Ejercicios> Mostrar_Ejercicios_Por_Profundidad_Del_Enunciado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Enunciado", DbType="NVarChar(MAX)")] string enunciado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), enunciado);
			return ((ISingleResult<Tabla_MATH_De_Ejercicios>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Buscar_En_Tabla_Colegios")]
		public ISingleResult<Tabla_De_Colegios> Buscar_En_Tabla_Colegios([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Colegio", DbType="NVarChar(150)")] string colegio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), colegio);
			return ((ISingleResult<Tabla_De_Colegios>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Buscar_En_Tabla_Materias")]
		public ISingleResult<Tabla_De_Materias> Buscar_En_Tabla_Materias([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Materia", DbType="NVarChar(150)")] string materia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), materia);
			return ((ISingleResult<Tabla_De_Materias>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Buscar_En_Tabla_Profesores")]
		public ISingleResult<Tabla_De_Profesores> Buscar_En_Tabla_Profesores([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Profesor", DbType="NVarChar(150)")] string profesor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), profesor);
			return ((ISingleResult<Tabla_De_Profesores>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Buscar_En_Tabla_Temas")]
		public ISingleResult<Tabla_De_Temas> Buscar_En_Tabla_Temas([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tema", DbType="NVarChar(150)")] string tema)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tema);
			return ((ISingleResult<Tabla_De_Temas>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Contar_Ejercicios_Por_Ficha_Completa")]
		public int Contar_Ejercicios_Por_Ficha_Completa([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Profesor", DbType="NVarChar(150)")] string profesor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ano", DbType="NVarChar(150)")] string ano, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Colegio", DbType="NVarChar(150)")] string colegio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Materia", DbType="NVarChar(150)")] string materia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tema", DbType="NVarChar(150)")] string tema, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] ref System.Nullable<int> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), profesor, ano, colegio, materia, tema, cantidad);
			cantidad = ((System.Nullable<int>)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Contar_Ejercicios_Por_Institucion")]
		public int Contar_Ejercicios_Por_Institucion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Institucion", DbType="Int")] System.Nullable<int> institucion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] ref System.Nullable<int> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), institucion, cantidad);
			cantidad = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Contar_Ejercicios_Por_Palabras_Claves_Del_Enunciado")]
		public int Contar_Ejercicios_Por_Palabras_Claves_Del_Enunciado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var1", DbType="NVarChar(20)")] string var1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var2", DbType="NVarChar(20)")] string var2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var3", DbType="NVarChar(20)")] string var3, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var4", DbType="NVarChar(20)")] string var4, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var5", DbType="NVarChar(20)")] string var5, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var6", DbType="NVarChar(20)")] string var6, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var7", DbType="NVarChar(20)")] string var7, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var8", DbType="NVarChar(20)")] string var8, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var9", DbType="NVarChar(20)")] string var9, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var10", DbType="NVarChar(20)")] string var10, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] ref System.Nullable<int> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), var1, var2, var3, var4, var5, var6, var7, var8, var9, var10, cantidad);
			cantidad = ((System.Nullable<int>)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Contar_Ejercicios_Por_Profundidad_Del_Enunciado")]
		public int Contar_Ejercicios_Por_Profundidad_Del_Enunciado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Enunciado", DbType="NVarChar(MAX)")] string enunciado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] ref System.Nullable<int> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), enunciado, cantidad);
			cantidad = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Logueo_Administrador")]
		public int Logueo_Administrador([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Administrador", DbType="NVarChar(10)")] string administrador, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(10)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Empresa", DbType="NVarChar(20)")] string empresa, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IP_Address", DbType="NVarChar(20)")] string iP_Address, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ingresos", DbType="Int")] System.Nullable<int> ingresos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Categoria", DbType="Int")] ref System.Nullable<int> categoria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Administrador", DbType="Int")] ref System.Nullable<int> iD_Administrador, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID_Empresa", DbType="Int")] ref System.Nullable<int> iD_Empresa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), administrador, password, empresa, iP_Address, ingresos, categoria, iD_Administrador, iD_Empresa);
			categoria = ((System.Nullable<int>)(result.GetParameterValue(5)));
			iD_Administrador = ((System.Nullable<int>)(result.GetParameterValue(6)));
			iD_Empresa = ((System.Nullable<int>)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Mostrar_Ejercicios_Por_Ficha_Completa")]
		public ISingleResult<Tabla_De_Ejercicios> Mostrar_Ejercicios_Por_Ficha_Completa([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Profesor", DbType="NVarChar(150)")] string profesor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ano", DbType="NVarChar(150)")] string ano, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Colegio", DbType="NVarChar(150)")] string colegio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Materia", DbType="NVarChar(150)")] string materia, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tema", DbType="NVarChar(150)")] string tema)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), profesor, ano, colegio, materia, tema);
			return ((ISingleResult<Tabla_De_Ejercicios>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Mostrar_Ejercicios_Por_Institucion")]
		public ISingleResult<Tabla_De_Ejercicios> Mostrar_Ejercicios_Por_Institucion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Institucion", DbType="Int")] System.Nullable<int> institucion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), institucion);
			return ((ISingleResult<Tabla_De_Ejercicios>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Mostrar_Ejercicios_Por_Palabras_Claves_Del_Enunciado")]
		public ISingleResult<Vista_Buscar_Ejercicios> Mostrar_Ejercicios_Por_Palabras_Claves_Del_Enunciado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var1", DbType="NVarChar(20)")] string var1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var2", DbType="NVarChar(20)")] string var2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var3", DbType="NVarChar(20)")] string var3, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var4", DbType="NVarChar(20)")] string var4, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var5", DbType="NVarChar(20)")] string var5, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var6", DbType="NVarChar(20)")] string var6, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var7", DbType="NVarChar(20)")] string var7, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var8", DbType="NVarChar(20)")] string var8, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var9", DbType="NVarChar(20)")] string var9, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var10", DbType="NVarChar(20)")] string var10)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), var1, var2, var3, var4, var5, var6, var7, var8, var9, var10);
			return ((ISingleResult<Vista_Buscar_Ejercicios>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Mostrar_Videos_Por_Palabras_Claves_Del_Enunciado")]
		public ISingleResult<Vista_Buscar_Videos> Mostrar_Videos_Por_Palabras_Claves_Del_Enunciado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var1", DbType="NVarChar(20)")] string var1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var2", DbType="NVarChar(20)")] string var2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var3", DbType="NVarChar(20)")] string var3, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var4", DbType="NVarChar(20)")] string var4, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var5", DbType="NVarChar(20)")] string var5, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var6", DbType="NVarChar(20)")] string var6, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var7", DbType="NVarChar(20)")] string var7, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var8", DbType="NVarChar(20)")] string var8, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var9", DbType="NVarChar(20)")] string var9, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var10", DbType="NVarChar(20)")] string var10)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), var1, var2, var3, var4, var5, var6, var7, var8, var9, var10);
			return ((ISingleResult<Vista_Buscar_Videos>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Contar_Videos_Por_Palabras_Claves_Del_Enunciado")]
		public int Contar_Videos_Por_Palabras_Claves_Del_Enunciado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var1", DbType="NVarChar(20)")] string var1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var2", DbType="NVarChar(20)")] string var2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var3", DbType="NVarChar(20)")] string var3, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var4", DbType="NVarChar(20)")] string var4, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var5", DbType="NVarChar(20)")] string var5, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var6", DbType="NVarChar(20)")] string var6, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var7", DbType="NVarChar(20)")] string var7, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var8", DbType="NVarChar(20)")] string var8, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var9", DbType="NVarChar(20)")] string var9, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Var10", DbType="NVarChar(20)")] string var10, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] ref System.Nullable<int> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), var1, var2, var3, var4, var5, var6, var7, var8, var9, var10, cantidad);
			cantidad = ((System.Nullable<int>)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Mostrar_Ejercicios_Por_Porcentaje_Del_Enunciado")]
		public ISingleResult<Tabla_MATH_De_Ejercicios> Mostrar_Ejercicios_Por_Porcentaje_Del_Enunciado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Enunciado_1", DbType="NVarChar(150)")] string enunciado_1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Enunciado_2", DbType="NVarChar(150)")] string enunciado_2)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), enunciado_1, enunciado_2);
			return ((ISingleResult<Tabla_MATH_De_Ejercicios>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Contar_Ejercicios_Por_Porcentaje_Del_Enunciado")]
		public int Contar_Ejercicios_Por_Porcentaje_Del_Enunciado([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Enunciado_1", DbType="NVarChar(150)")] string enunciado_1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Enunciado_2", DbType="NVarChar(150)")] string enunciado_2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] ref System.Nullable<int> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), enunciado_1, enunciado_2, cantidad);
			cantidad = ((System.Nullable<int>)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_Ubicacion_De_Los_Ejercicios")]
	public partial class Tabla_Ubicacion_De_Los_Ejercicios
	{
		
		private int _ID_Ejercicio;
		
		private string _Ubicacion_Respuesta_Imprimible;
		
		private string _Ubicacion_Respuesta_Visible;
		
		private string _Ubicacion_Videos_Y_Explicaciones;
		
		public Tabla_Ubicacion_De_Los_Ejercicios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Ejercicio", DbType="Int NOT NULL")]
		public int ID_Ejercicio
		{
			get
			{
				return this._ID_Ejercicio;
			}
			set
			{
				if ((this._ID_Ejercicio != value))
				{
					this._ID_Ejercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicacion_Respuesta_Imprimible", DbType="NVarChar(40)")]
		public string Ubicacion_Respuesta_Imprimible
		{
			get
			{
				return this._Ubicacion_Respuesta_Imprimible;
			}
			set
			{
				if ((this._Ubicacion_Respuesta_Imprimible != value))
				{
					this._Ubicacion_Respuesta_Imprimible = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicacion_Respuesta_Visible", DbType="NVarChar(40)")]
		public string Ubicacion_Respuesta_Visible
		{
			get
			{
				return this._Ubicacion_Respuesta_Visible;
			}
			set
			{
				if ((this._Ubicacion_Respuesta_Visible != value))
				{
					this._Ubicacion_Respuesta_Visible = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicacion_Videos_Y_Explicaciones", DbType="NVarChar(100)")]
		public string Ubicacion_Videos_Y_Explicaciones
		{
			get
			{
				return this._Ubicacion_Videos_Y_Explicaciones;
			}
			set
			{
				if ((this._Ubicacion_Videos_Y_Explicaciones != value))
				{
					this._Ubicacion_Videos_Y_Explicaciones = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_Busqueda_De_Ejercicios_Por_Etiquetas")]
	public partial class Tabla_Busqueda_De_Ejercicios_Por_Etiquetas
	{
		
		private int _ID_Ejercicio;
		
		private string _Etiqueta_Busqueda_Profesor;
		
		private string _Etiqueta_Busqueda_Ano;
		
		private string _Etiqueta_Busqueda_Colegio;
		
		private string _Etiqueta_Busqueda_Materia;
		
		private string _Etiqueta_Busqueda_Tema;
		
		public Tabla_Busqueda_De_Ejercicios_Por_Etiquetas()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Ejercicio", DbType="Int NOT NULL")]
		public int ID_Ejercicio
		{
			get
			{
				return this._ID_Ejercicio;
			}
			set
			{
				if ((this._ID_Ejercicio != value))
				{
					this._ID_Ejercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiqueta_Busqueda_Profesor", DbType="NVarChar(60)")]
		public string Etiqueta_Busqueda_Profesor
		{
			get
			{
				return this._Etiqueta_Busqueda_Profesor;
			}
			set
			{
				if ((this._Etiqueta_Busqueda_Profesor != value))
				{
					this._Etiqueta_Busqueda_Profesor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiqueta_Busqueda_Ano", DbType="NVarChar(60)")]
		public string Etiqueta_Busqueda_Ano
		{
			get
			{
				return this._Etiqueta_Busqueda_Ano;
			}
			set
			{
				if ((this._Etiqueta_Busqueda_Ano != value))
				{
					this._Etiqueta_Busqueda_Ano = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiqueta_Busqueda_Colegio", DbType="NVarChar(60)")]
		public string Etiqueta_Busqueda_Colegio
		{
			get
			{
				return this._Etiqueta_Busqueda_Colegio;
			}
			set
			{
				if ((this._Etiqueta_Busqueda_Colegio != value))
				{
					this._Etiqueta_Busqueda_Colegio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiqueta_Busqueda_Materia", DbType="NVarChar(60)")]
		public string Etiqueta_Busqueda_Materia
		{
			get
			{
				return this._Etiqueta_Busqueda_Materia;
			}
			set
			{
				if ((this._Etiqueta_Busqueda_Materia != value))
				{
					this._Etiqueta_Busqueda_Materia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiqueta_Busqueda_Tema", DbType="NVarChar(60)")]
		public string Etiqueta_Busqueda_Tema
		{
			get
			{
				return this._Etiqueta_Busqueda_Tema;
			}
			set
			{
				if ((this._Etiqueta_Busqueda_Tema != value))
				{
					this._Etiqueta_Busqueda_Tema = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_De_Administradores")]
	public partial class Tabla_De_Administradores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Administrador;
		
		private string _Administrador;
		
		private int _Categoria;
		
		private string _Password;
		
		private int _ID_Empresa;
		
		private bool _Administrador_Bloqueado;
		
		private string _IP_Address;
		
		private EntityRef<Tabla_De_Empresas> _Tabla_De_Empresas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_AdministradorChanging(int value);
    partial void OnID_AdministradorChanged();
    partial void OnAdministradorChanging(string value);
    partial void OnAdministradorChanged();
    partial void OnCategoriaChanging(int value);
    partial void OnCategoriaChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnID_EmpresaChanging(int value);
    partial void OnID_EmpresaChanged();
    partial void OnAdministrador_BloqueadoChanging(bool value);
    partial void OnAdministrador_BloqueadoChanged();
    partial void OnIP_AddressChanging(string value);
    partial void OnIP_AddressChanged();
    #endregion
		
		public Tabla_De_Administradores()
		{
			this._Tabla_De_Empresas = default(EntityRef<Tabla_De_Empresas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Administrador", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Administrador
		{
			get
			{
				return this._ID_Administrador;
			}
			set
			{
				if ((this._ID_Administrador != value))
				{
					this.OnID_AdministradorChanging(value);
					this.SendPropertyChanging();
					this._ID_Administrador = value;
					this.SendPropertyChanged("ID_Administrador");
					this.OnID_AdministradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Administrador", DbType="NVarChar(10)")]
		public string Administrador
		{
			get
			{
				return this._Administrador;
			}
			set
			{
				if ((this._Administrador != value))
				{
					this.OnAdministradorChanging(value);
					this.SendPropertyChanging();
					this._Administrador = value;
					this.SendPropertyChanged("Administrador");
					this.OnAdministradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="Int NOT NULL")]
		public int Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Empresa", DbType="Int NOT NULL")]
		public int ID_Empresa
		{
			get
			{
				return this._ID_Empresa;
			}
			set
			{
				if ((this._ID_Empresa != value))
				{
					if (this._Tabla_De_Empresas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_EmpresaChanging(value);
					this.SendPropertyChanging();
					this._ID_Empresa = value;
					this.SendPropertyChanged("ID_Empresa");
					this.OnID_EmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Administrador_Bloqueado", DbType="Bit NOT NULL")]
		public bool Administrador_Bloqueado
		{
			get
			{
				return this._Administrador_Bloqueado;
			}
			set
			{
				if ((this._Administrador_Bloqueado != value))
				{
					this.OnAdministrador_BloqueadoChanging(value);
					this.SendPropertyChanging();
					this._Administrador_Bloqueado = value;
					this.SendPropertyChanged("Administrador_Bloqueado");
					this.OnAdministrador_BloqueadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP_Address", DbType="NVarChar(20)")]
		public string IP_Address
		{
			get
			{
				return this._IP_Address;
			}
			set
			{
				if ((this._IP_Address != value))
				{
					this.OnIP_AddressChanging(value);
					this.SendPropertyChanging();
					this._IP_Address = value;
					this.SendPropertyChanged("IP_Address");
					this.OnIP_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabla_De_Empresas_Tabla_De_Administradores", Storage="_Tabla_De_Empresas", ThisKey="ID_Empresa", OtherKey="ID_Empresa", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Tabla_De_Empresas Tabla_De_Empresas
		{
			get
			{
				return this._Tabla_De_Empresas.Entity;
			}
			set
			{
				Tabla_De_Empresas previousValue = this._Tabla_De_Empresas.Entity;
				if (((previousValue != value) 
							|| (this._Tabla_De_Empresas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tabla_De_Empresas.Entity = null;
						previousValue.Tabla_De_Administradores.Remove(this);
					}
					this._Tabla_De_Empresas.Entity = value;
					if ((value != null))
					{
						value.Tabla_De_Administradores.Add(this);
						this._ID_Empresa = value.ID_Empresa;
					}
					else
					{
						this._ID_Empresa = default(int);
					}
					this.SendPropertyChanged("Tabla_De_Empresas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_De_Anos")]
	public partial class Tabla_De_Anos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Ano;
		
		private string _Ano;
		
		private int _Etiqueta_Ano;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_AnoChanging(int value);
    partial void OnID_AnoChanged();
    partial void OnAnoChanging(string value);
    partial void OnAnoChanged();
    partial void OnEtiqueta_AnoChanging(int value);
    partial void OnEtiqueta_AnoChanged();
    #endregion
		
		public Tabla_De_Anos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Ano", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Ano
		{
			get
			{
				return this._ID_Ano;
			}
			set
			{
				if ((this._ID_Ano != value))
				{
					this.OnID_AnoChanging(value);
					this.SendPropertyChanging();
					this._ID_Ano = value;
					this.SendPropertyChanged("ID_Ano");
					this.OnID_AnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ano", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Ano
		{
			get
			{
				return this._Ano;
			}
			set
			{
				if ((this._Ano != value))
				{
					this.OnAnoChanging(value);
					this.SendPropertyChanging();
					this._Ano = value;
					this.SendPropertyChanged("Ano");
					this.OnAnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiqueta_Ano", DbType="Int NOT NULL")]
		public int Etiqueta_Ano
		{
			get
			{
				return this._Etiqueta_Ano;
			}
			set
			{
				if ((this._Etiqueta_Ano != value))
				{
					this.OnEtiqueta_AnoChanging(value);
					this.SendPropertyChanging();
					this._Etiqueta_Ano = value;
					this.SendPropertyChanged("Etiqueta_Ano");
					this.OnEtiqueta_AnoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_De_Colegios")]
	public partial class Tabla_De_Colegios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Colegio;
		
		private string _Colegio;
		
		private int _Etiqueta_Colegio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ColegioChanging(int value);
    partial void OnID_ColegioChanged();
    partial void OnColegioChanging(string value);
    partial void OnColegioChanged();
    partial void OnEtiqueta_ColegioChanging(int value);
    partial void OnEtiqueta_ColegioChanged();
    #endregion
		
		public Tabla_De_Colegios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Colegio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Colegio
		{
			get
			{
				return this._ID_Colegio;
			}
			set
			{
				if ((this._ID_Colegio != value))
				{
					this.OnID_ColegioChanging(value);
					this.SendPropertyChanging();
					this._ID_Colegio = value;
					this.SendPropertyChanged("ID_Colegio");
					this.OnID_ColegioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Colegio", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Colegio
		{
			get
			{
				return this._Colegio;
			}
			set
			{
				if ((this._Colegio != value))
				{
					this.OnColegioChanging(value);
					this.SendPropertyChanging();
					this._Colegio = value;
					this.SendPropertyChanged("Colegio");
					this.OnColegioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiqueta_Colegio", DbType="Int NOT NULL")]
		public int Etiqueta_Colegio
		{
			get
			{
				return this._Etiqueta_Colegio;
			}
			set
			{
				if ((this._Etiqueta_Colegio != value))
				{
					this.OnEtiqueta_ColegioChanging(value);
					this.SendPropertyChanging();
					this._Etiqueta_Colegio = value;
					this.SendPropertyChanged("Etiqueta_Colegio");
					this.OnEtiqueta_ColegioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_De_Ejercicios")]
	public partial class Tabla_De_Ejercicios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Ejercicio;
		
		private string _Titulo;
		
		private System.Nullable<int> _ID_Tipo_De_Ejercicio;
		
		private System.Nullable<int> _ID_Tipo_De_Institucion;
		
		private bool _Explicacion_Realizada;
		
		private EntityRef<Tabla_Tipo_De_Institucion> _Tabla_Tipo_De_Institucion;
		
		private EntityRef<Tabla_Tipo_De_Producto> _Tabla_Tipo_De_Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EjercicioChanging(int value);
    partial void OnID_EjercicioChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    partial void OnID_Tipo_De_EjercicioChanging(System.Nullable<int> value);
    partial void OnID_Tipo_De_EjercicioChanged();
    partial void OnID_Tipo_De_InstitucionChanging(System.Nullable<int> value);
    partial void OnID_Tipo_De_InstitucionChanged();
    partial void OnExplicacion_RealizadaChanging(bool value);
    partial void OnExplicacion_RealizadaChanged();
    #endregion
		
		public Tabla_De_Ejercicios()
		{
			this._Tabla_Tipo_De_Institucion = default(EntityRef<Tabla_Tipo_De_Institucion>);
			this._Tabla_Tipo_De_Producto = default(EntityRef<Tabla_Tipo_De_Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Ejercicio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Ejercicio
		{
			get
			{
				return this._ID_Ejercicio;
			}
			set
			{
				if ((this._ID_Ejercicio != value))
				{
					this.OnID_EjercicioChanging(value);
					this.SendPropertyChanging();
					this._ID_Ejercicio = value;
					this.SendPropertyChanged("ID_Ejercicio");
					this.OnID_EjercicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Tipo_De_Ejercicio", DbType="Int")]
		public System.Nullable<int> ID_Tipo_De_Ejercicio
		{
			get
			{
				return this._ID_Tipo_De_Ejercicio;
			}
			set
			{
				if ((this._ID_Tipo_De_Ejercicio != value))
				{
					if (this._Tabla_Tipo_De_Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_Tipo_De_EjercicioChanging(value);
					this.SendPropertyChanging();
					this._ID_Tipo_De_Ejercicio = value;
					this.SendPropertyChanged("ID_Tipo_De_Ejercicio");
					this.OnID_Tipo_De_EjercicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Tipo_De_Institucion", DbType="Int")]
		public System.Nullable<int> ID_Tipo_De_Institucion
		{
			get
			{
				return this._ID_Tipo_De_Institucion;
			}
			set
			{
				if ((this._ID_Tipo_De_Institucion != value))
				{
					if (this._Tabla_Tipo_De_Institucion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_Tipo_De_InstitucionChanging(value);
					this.SendPropertyChanging();
					this._ID_Tipo_De_Institucion = value;
					this.SendPropertyChanged("ID_Tipo_De_Institucion");
					this.OnID_Tipo_De_InstitucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Explicacion_Realizada", DbType="Bit NOT NULL")]
		public bool Explicacion_Realizada
		{
			get
			{
				return this._Explicacion_Realizada;
			}
			set
			{
				if ((this._Explicacion_Realizada != value))
				{
					this.OnExplicacion_RealizadaChanging(value);
					this.SendPropertyChanging();
					this._Explicacion_Realizada = value;
					this.SendPropertyChanged("Explicacion_Realizada");
					this.OnExplicacion_RealizadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabla_Tipo_De_Institucion_Tabla_De_Ejercicios", Storage="_Tabla_Tipo_De_Institucion", ThisKey="ID_Tipo_De_Institucion", OtherKey="ID_Tipo_De_Institucion", IsForeignKey=true, DeleteRule="CASCADE")]
		public Tabla_Tipo_De_Institucion Tabla_Tipo_De_Institucion
		{
			get
			{
				return this._Tabla_Tipo_De_Institucion.Entity;
			}
			set
			{
				Tabla_Tipo_De_Institucion previousValue = this._Tabla_Tipo_De_Institucion.Entity;
				if (((previousValue != value) 
							|| (this._Tabla_Tipo_De_Institucion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tabla_Tipo_De_Institucion.Entity = null;
						previousValue.Tabla_De_Ejercicios.Remove(this);
					}
					this._Tabla_Tipo_De_Institucion.Entity = value;
					if ((value != null))
					{
						value.Tabla_De_Ejercicios.Add(this);
						this._ID_Tipo_De_Institucion = value.ID_Tipo_De_Institucion;
					}
					else
					{
						this._ID_Tipo_De_Institucion = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tabla_Tipo_De_Institucion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabla_Tipo_De_Producto_Tabla_De_Ejercicios", Storage="_Tabla_Tipo_De_Producto", ThisKey="ID_Tipo_De_Ejercicio", OtherKey="ID_Tipo_De_Ejercicio", IsForeignKey=true, DeleteRule="CASCADE")]
		public Tabla_Tipo_De_Producto Tabla_Tipo_De_Producto
		{
			get
			{
				return this._Tabla_Tipo_De_Producto.Entity;
			}
			set
			{
				Tabla_Tipo_De_Producto previousValue = this._Tabla_Tipo_De_Producto.Entity;
				if (((previousValue != value) 
							|| (this._Tabla_Tipo_De_Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tabla_Tipo_De_Producto.Entity = null;
						previousValue.Tabla_De_Ejercicios.Remove(this);
					}
					this._Tabla_Tipo_De_Producto.Entity = value;
					if ((value != null))
					{
						value.Tabla_De_Ejercicios.Add(this);
						this._ID_Tipo_De_Ejercicio = value.ID_Tipo_De_Ejercicio;
					}
					else
					{
						this._ID_Tipo_De_Ejercicio = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tabla_Tipo_De_Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_De_Empresas")]
	public partial class Tabla_De_Empresas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Empresa;
		
		private string _Empresa;
		
		private EntitySet<Tabla_De_Administradores> _Tabla_De_Administradores;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_EmpresaChanging(int value);
    partial void OnID_EmpresaChanged();
    partial void OnEmpresaChanging(string value);
    partial void OnEmpresaChanged();
    #endregion
		
		public Tabla_De_Empresas()
		{
			this._Tabla_De_Administradores = new EntitySet<Tabla_De_Administradores>(new Action<Tabla_De_Administradores>(this.attach_Tabla_De_Administradores), new Action<Tabla_De_Administradores>(this.detach_Tabla_De_Administradores));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Empresa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Empresa
		{
			get
			{
				return this._ID_Empresa;
			}
			set
			{
				if ((this._ID_Empresa != value))
				{
					this.OnID_EmpresaChanging(value);
					this.SendPropertyChanging();
					this._ID_Empresa = value;
					this.SendPropertyChanged("ID_Empresa");
					this.OnID_EmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empresa", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Empresa
		{
			get
			{
				return this._Empresa;
			}
			set
			{
				if ((this._Empresa != value))
				{
					this.OnEmpresaChanging(value);
					this.SendPropertyChanging();
					this._Empresa = value;
					this.SendPropertyChanged("Empresa");
					this.OnEmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabla_De_Empresas_Tabla_De_Administradores", Storage="_Tabla_De_Administradores", ThisKey="ID_Empresa", OtherKey="ID_Empresa")]
		public EntitySet<Tabla_De_Administradores> Tabla_De_Administradores
		{
			get
			{
				return this._Tabla_De_Administradores;
			}
			set
			{
				this._Tabla_De_Administradores.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tabla_De_Administradores(Tabla_De_Administradores entity)
		{
			this.SendPropertyChanging();
			entity.Tabla_De_Empresas = this;
		}
		
		private void detach_Tabla_De_Administradores(Tabla_De_Administradores entity)
		{
			this.SendPropertyChanging();
			entity.Tabla_De_Empresas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_De_Materias")]
	public partial class Tabla_De_Materias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Materia;
		
		private string _Materia;
		
		private int _Etiqueta_Materia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MateriaChanging(int value);
    partial void OnID_MateriaChanged();
    partial void OnMateriaChanging(string value);
    partial void OnMateriaChanged();
    partial void OnEtiqueta_MateriaChanging(int value);
    partial void OnEtiqueta_MateriaChanged();
    #endregion
		
		public Tabla_De_Materias()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Materia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Materia
		{
			get
			{
				return this._ID_Materia;
			}
			set
			{
				if ((this._ID_Materia != value))
				{
					this.OnID_MateriaChanging(value);
					this.SendPropertyChanging();
					this._ID_Materia = value;
					this.SendPropertyChanged("ID_Materia");
					this.OnID_MateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Materia", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Materia
		{
			get
			{
				return this._Materia;
			}
			set
			{
				if ((this._Materia != value))
				{
					this.OnMateriaChanging(value);
					this.SendPropertyChanging();
					this._Materia = value;
					this.SendPropertyChanged("Materia");
					this.OnMateriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiqueta_Materia", DbType="Int NOT NULL")]
		public int Etiqueta_Materia
		{
			get
			{
				return this._Etiqueta_Materia;
			}
			set
			{
				if ((this._Etiqueta_Materia != value))
				{
					this.OnEtiqueta_MateriaChanging(value);
					this.SendPropertyChanging();
					this._Etiqueta_Materia = value;
					this.SendPropertyChanged("Etiqueta_Materia");
					this.OnEtiqueta_MateriaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_De_Profesores")]
	public partial class Tabla_De_Profesores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Profesor;
		
		private string _Profesor;
		
		private int _Etiqueta_Profesor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ProfesorChanging(int value);
    partial void OnID_ProfesorChanged();
    partial void OnProfesorChanging(string value);
    partial void OnProfesorChanged();
    partial void OnEtiqueta_ProfesorChanging(int value);
    partial void OnEtiqueta_ProfesorChanged();
    #endregion
		
		public Tabla_De_Profesores()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Profesor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Profesor
		{
			get
			{
				return this._ID_Profesor;
			}
			set
			{
				if ((this._ID_Profesor != value))
				{
					this.OnID_ProfesorChanging(value);
					this.SendPropertyChanging();
					this._ID_Profesor = value;
					this.SendPropertyChanged("ID_Profesor");
					this.OnID_ProfesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profesor", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Profesor
		{
			get
			{
				return this._Profesor;
			}
			set
			{
				if ((this._Profesor != value))
				{
					this.OnProfesorChanging(value);
					this.SendPropertyChanging();
					this._Profesor = value;
					this.SendPropertyChanged("Profesor");
					this.OnProfesorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiqueta_Profesor", DbType="Int NOT NULL")]
		public int Etiqueta_Profesor
		{
			get
			{
				return this._Etiqueta_Profesor;
			}
			set
			{
				if ((this._Etiqueta_Profesor != value))
				{
					this.OnEtiqueta_ProfesorChanging(value);
					this.SendPropertyChanging();
					this._Etiqueta_Profesor = value;
					this.SendPropertyChanged("Etiqueta_Profesor");
					this.OnEtiqueta_ProfesorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_De_Temas")]
	public partial class Tabla_De_Temas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Tema;
		
		private string _Tema;
		
		private int _Etiqueta_Tema;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TemaChanging(int value);
    partial void OnID_TemaChanged();
    partial void OnTemaChanging(string value);
    partial void OnTemaChanged();
    partial void OnEtiqueta_TemaChanging(int value);
    partial void OnEtiqueta_TemaChanged();
    #endregion
		
		public Tabla_De_Temas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Tema", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Tema
		{
			get
			{
				return this._ID_Tema;
			}
			set
			{
				if ((this._ID_Tema != value))
				{
					this.OnID_TemaChanging(value);
					this.SendPropertyChanging();
					this._ID_Tema = value;
					this.SendPropertyChanged("ID_Tema");
					this.OnID_TemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tema", DbType="NVarChar(60) NOT NULL", CanBeNull=false)]
		public string Tema
		{
			get
			{
				return this._Tema;
			}
			set
			{
				if ((this._Tema != value))
				{
					this.OnTemaChanging(value);
					this.SendPropertyChanging();
					this._Tema = value;
					this.SendPropertyChanged("Tema");
					this.OnTemaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etiqueta_Tema", DbType="Int NOT NULL")]
		public int Etiqueta_Tema
		{
			get
			{
				return this._Etiqueta_Tema;
			}
			set
			{
				if ((this._Etiqueta_Tema != value))
				{
					this.OnEtiqueta_TemaChanging(value);
					this.SendPropertyChanging();
					this._Etiqueta_Tema = value;
					this.SendPropertyChanged("Etiqueta_Tema");
					this.OnEtiqueta_TemaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_MATH_De_Ejercicios")]
	public partial class Tabla_MATH_De_Ejercicios
	{
		
		private int _ID_Ejercicio;
		
		private string _Enunciado_MATH;
		
		private string _Enunciado_Limpio;
		
		public Tabla_MATH_De_Ejercicios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Ejercicio", DbType="Int NOT NULL")]
		public int ID_Ejercicio
		{
			get
			{
				return this._ID_Ejercicio;
			}
			set
			{
				if ((this._ID_Ejercicio != value))
				{
					this._ID_Ejercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enunciado_MATH", DbType="NVarChar(MAX)")]
		public string Enunciado_MATH
		{
			get
			{
				return this._Enunciado_MATH;
			}
			set
			{
				if ((this._Enunciado_MATH != value))
				{
					this._Enunciado_MATH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enunciado_Limpio", DbType="NVarChar(MAX)")]
		public string Enunciado_Limpio
		{
			get
			{
				return this._Enunciado_Limpio;
			}
			set
			{
				if ((this._Enunciado_Limpio != value))
				{
					this._Enunciado_Limpio = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_Tipo_De_Institucion")]
	public partial class Tabla_Tipo_De_Institucion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Tipo_De_Institucion;
		
		private string _Tipo_De_Institucion;
		
		private EntitySet<Tabla_De_Ejercicios> _Tabla_De_Ejercicios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Tipo_De_InstitucionChanging(int value);
    partial void OnID_Tipo_De_InstitucionChanged();
    partial void OnTipo_De_InstitucionChanging(string value);
    partial void OnTipo_De_InstitucionChanged();
    #endregion
		
		public Tabla_Tipo_De_Institucion()
		{
			this._Tabla_De_Ejercicios = new EntitySet<Tabla_De_Ejercicios>(new Action<Tabla_De_Ejercicios>(this.attach_Tabla_De_Ejercicios), new Action<Tabla_De_Ejercicios>(this.detach_Tabla_De_Ejercicios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Tipo_De_Institucion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Tipo_De_Institucion
		{
			get
			{
				return this._ID_Tipo_De_Institucion;
			}
			set
			{
				if ((this._ID_Tipo_De_Institucion != value))
				{
					this.OnID_Tipo_De_InstitucionChanging(value);
					this.SendPropertyChanging();
					this._ID_Tipo_De_Institucion = value;
					this.SendPropertyChanged("ID_Tipo_De_Institucion");
					this.OnID_Tipo_De_InstitucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_De_Institucion", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Tipo_De_Institucion
		{
			get
			{
				return this._Tipo_De_Institucion;
			}
			set
			{
				if ((this._Tipo_De_Institucion != value))
				{
					this.OnTipo_De_InstitucionChanging(value);
					this.SendPropertyChanging();
					this._Tipo_De_Institucion = value;
					this.SendPropertyChanged("Tipo_De_Institucion");
					this.OnTipo_De_InstitucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabla_Tipo_De_Institucion_Tabla_De_Ejercicios", Storage="_Tabla_De_Ejercicios", ThisKey="ID_Tipo_De_Institucion", OtherKey="ID_Tipo_De_Institucion")]
		public EntitySet<Tabla_De_Ejercicios> Tabla_De_Ejercicios
		{
			get
			{
				return this._Tabla_De_Ejercicios;
			}
			set
			{
				this._Tabla_De_Ejercicios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tabla_De_Ejercicios(Tabla_De_Ejercicios entity)
		{
			this.SendPropertyChanging();
			entity.Tabla_Tipo_De_Institucion = this;
		}
		
		private void detach_Tabla_De_Ejercicios(Tabla_De_Ejercicios entity)
		{
			this.SendPropertyChanging();
			entity.Tabla_Tipo_De_Institucion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tabla_Tipo_De_Producto")]
	public partial class Tabla_Tipo_De_Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Tipo_De_Ejercicio;
		
		private string _Tipo_De_Producto;
		
		private EntitySet<Tabla_De_Ejercicios> _Tabla_De_Ejercicios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Tipo_De_EjercicioChanging(int value);
    partial void OnID_Tipo_De_EjercicioChanged();
    partial void OnTipo_De_ProductoChanging(string value);
    partial void OnTipo_De_ProductoChanged();
    #endregion
		
		public Tabla_Tipo_De_Producto()
		{
			this._Tabla_De_Ejercicios = new EntitySet<Tabla_De_Ejercicios>(new Action<Tabla_De_Ejercicios>(this.attach_Tabla_De_Ejercicios), new Action<Tabla_De_Ejercicios>(this.detach_Tabla_De_Ejercicios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Tipo_De_Ejercicio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Tipo_De_Ejercicio
		{
			get
			{
				return this._ID_Tipo_De_Ejercicio;
			}
			set
			{
				if ((this._ID_Tipo_De_Ejercicio != value))
				{
					this.OnID_Tipo_De_EjercicioChanging(value);
					this.SendPropertyChanging();
					this._ID_Tipo_De_Ejercicio = value;
					this.SendPropertyChanged("ID_Tipo_De_Ejercicio");
					this.OnID_Tipo_De_EjercicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_De_Producto", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Tipo_De_Producto
		{
			get
			{
				return this._Tipo_De_Producto;
			}
			set
			{
				if ((this._Tipo_De_Producto != value))
				{
					this.OnTipo_De_ProductoChanging(value);
					this.SendPropertyChanging();
					this._Tipo_De_Producto = value;
					this.SendPropertyChanged("Tipo_De_Producto");
					this.OnTipo_De_ProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tabla_Tipo_De_Producto_Tabla_De_Ejercicios", Storage="_Tabla_De_Ejercicios", ThisKey="ID_Tipo_De_Ejercicio", OtherKey="ID_Tipo_De_Ejercicio")]
		public EntitySet<Tabla_De_Ejercicios> Tabla_De_Ejercicios
		{
			get
			{
				return this._Tabla_De_Ejercicios;
			}
			set
			{
				this._Tabla_De_Ejercicios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tabla_De_Ejercicios(Tabla_De_Ejercicios entity)
		{
			this.SendPropertyChanging();
			entity.Tabla_Tipo_De_Producto = this;
		}
		
		private void detach_Tabla_De_Ejercicios(Tabla_De_Ejercicios entity)
		{
			this.SendPropertyChanging();
			entity.Tabla_Tipo_De_Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vista_Administradores")]
	public partial class Vista_Administradores
	{
		
		private int _ID_Administrador;
		
		private string _Administrador;
		
		private int _Categoria;
		
		private string _Password;
		
		private bool _Administrador_Bloqueado;
		
		private string _IP_Address;
		
		private string _Empresa;
		
		public Vista_Administradores()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Administrador", DbType="Int NOT NULL")]
		public int ID_Administrador
		{
			get
			{
				return this._ID_Administrador;
			}
			set
			{
				if ((this._ID_Administrador != value))
				{
					this._ID_Administrador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Administrador", DbType="NVarChar(10)")]
		public string Administrador
		{
			get
			{
				return this._Administrador;
			}
			set
			{
				if ((this._Administrador != value))
				{
					this._Administrador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="Int NOT NULL")]
		public int Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Administrador_Bloqueado", DbType="Bit NOT NULL")]
		public bool Administrador_Bloqueado
		{
			get
			{
				return this._Administrador_Bloqueado;
			}
			set
			{
				if ((this._Administrador_Bloqueado != value))
				{
					this._Administrador_Bloqueado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP_Address", DbType="NVarChar(20)")]
		public string IP_Address
		{
			get
			{
				return this._IP_Address;
			}
			set
			{
				if ((this._IP_Address != value))
				{
					this._IP_Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empresa", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Empresa
		{
			get
			{
				return this._Empresa;
			}
			set
			{
				if ((this._Empresa != value))
				{
					this._Empresa = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vista_Buscar_Ejercicios")]
	public partial class Vista_Buscar_Ejercicios
	{
		
		private System.Nullable<int> _ID_Tipo_De_Ejercicio;
		
		private int _ID_Ejercicio;
		
		private string _Ubicacion_Respuesta_Imprimible;
		
		private string _Enunciado_Limpio;
		
		public Vista_Buscar_Ejercicios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Tipo_De_Ejercicio", DbType="Int")]
		public System.Nullable<int> ID_Tipo_De_Ejercicio
		{
			get
			{
				return this._ID_Tipo_De_Ejercicio;
			}
			set
			{
				if ((this._ID_Tipo_De_Ejercicio != value))
				{
					this._ID_Tipo_De_Ejercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Ejercicio", DbType="Int NOT NULL")]
		public int ID_Ejercicio
		{
			get
			{
				return this._ID_Ejercicio;
			}
			set
			{
				if ((this._ID_Ejercicio != value))
				{
					this._ID_Ejercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicacion_Respuesta_Imprimible", DbType="NVarChar(40)")]
		public string Ubicacion_Respuesta_Imprimible
		{
			get
			{
				return this._Ubicacion_Respuesta_Imprimible;
			}
			set
			{
				if ((this._Ubicacion_Respuesta_Imprimible != value))
				{
					this._Ubicacion_Respuesta_Imprimible = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enunciado_Limpio", DbType="NVarChar(MAX)")]
		public string Enunciado_Limpio
		{
			get
			{
				return this._Enunciado_Limpio;
			}
			set
			{
				if ((this._Enunciado_Limpio != value))
				{
					this._Enunciado_Limpio = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vista_Buscar_Videos")]
	public partial class Vista_Buscar_Videos
	{
		
		private string _Enunciado_Limpio;
		
		private string _Ubicacion_Videos_Y_Explicaciones;
		
		private int _ID_Ejercicio;
		
		private System.Nullable<int> _ID_Tipo_De_Ejercicio;
		
		public Vista_Buscar_Videos()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enunciado_Limpio", DbType="NVarChar(MAX)")]
		public string Enunciado_Limpio
		{
			get
			{
				return this._Enunciado_Limpio;
			}
			set
			{
				if ((this._Enunciado_Limpio != value))
				{
					this._Enunciado_Limpio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ubicacion_Videos_Y_Explicaciones", DbType="NVarChar(100)")]
		public string Ubicacion_Videos_Y_Explicaciones
		{
			get
			{
				return this._Ubicacion_Videos_Y_Explicaciones;
			}
			set
			{
				if ((this._Ubicacion_Videos_Y_Explicaciones != value))
				{
					this._Ubicacion_Videos_Y_Explicaciones = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Ejercicio", DbType="Int NOT NULL")]
		public int ID_Ejercicio
		{
			get
			{
				return this._ID_Ejercicio;
			}
			set
			{
				if ((this._ID_Ejercicio != value))
				{
					this._ID_Ejercicio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Tipo_De_Ejercicio", DbType="Int")]
		public System.Nullable<int> ID_Tipo_De_Ejercicio
		{
			get
			{
				return this._ID_Tipo_De_Ejercicio;
			}
			set
			{
				if ((this._ID_Tipo_De_Ejercicio != value))
				{
					this._ID_Tipo_De_Ejercicio = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
